
name: C++

on:
  push:
    branches:
      - {{ cookiecutter.default_branch }}
  pull_request:
    branches:
      - {{ cookiecutter.default_branch }}
  release:
    types:
      - published

jobs:
  build:
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        run: |
          mkdir -p lib/build
          cd lib/build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . --parallel 2

      - name: Run tests
        run: |
          cd c++/build
          ctest -C Debug
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
