name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        pymc-arviz:
          - '"pymc3~=3.9.0" "arviz<0.11"'
          - '"pymc3~=3.10.0" "arviz<0.11"'
          - '"pymc3~=3.11.0"'
          - '"https://github.com/pymc-devs/pymc3/archive/master.zip"'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      # Setup
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install ${{ matrix.pymc-arviz }}
          python -m pip install rebound
          python -m pip install "reboundx>=3.2.0"
          python -m pip install -e .[test]
          python -m pip install --no-deps starry rebound-pymc3
      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest --cov=exoplanet -v tests

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel: true
          flag-name: Unit Tests

  coverage:
    name: "Merge and upload coverage"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel-finished: true
